### ISSUE TITLE
Potentially move away from git LFS

### ISSUE THREAD

**Issue by maartenweyns** [WISVCH/chipcie-website#55]
Judging by the CH GitHub billing and quota tab, this website is growing to reach the limits of what we're allowed to use (at least bandwidth-wise):

![image](https://github.com/WISVCH/chipcie-website/assets/19886044/ce8697b1-7c0b-4fa7-bcd6-a03db9f1e5ee)

So maybe git LFS is not a long-term solution to store the archives. We could move to a google cloud bucket? Or maybe even a persistent volume in the cluster. Something to look at!

**Comment by verwoerd** [comment]
This bandwidth problem is caused by the builds AFAIK.  Every PR and following commits in the PR and pushes on main trigger a build. We already tried to tackle this by using the [`nschloe/action-cached-lfs-checkout@v1`](https://github.com/WISVCH/chipcie-website/blob/c47d0772d4141eded0f14633ae1f3178f434230d/.github/workflows/docker.yml#L14), but there seem to be [an issue](https://github.com/nschloe/action-cached-lfs-checkout/issues/27) when any LFS data is added, the cache is invalidated. We could attempt a direct solution as proposed [here](https://github.com/actions/checkout/issues/165#issuecomment-1639209867).

 I think a k8s PV is in my experience not easily accessible (only through `kubectl` and their derivatives afaik). No experience with Google cloud buckets, but i fear the access for uploading and link generation can be tricky to maintain long term. It is desirable that the new entries in the archive are published within a hour after the results are known (and there is no embargo).

**Comment by praseodym** [comment]
I've added another Git LFS data pack because we nearly ran out of bandwidth and have a 100% off coupon on our account anyway:
<img width="946" alt="Screenshot 2024-04-05 at 16 00 48" src="https://github.com/WISVCH/chipcie-website/assets/20283/a77cc04d-9170-4dd8-b074-8891a1266067">
<img width="953" alt="Screenshot 2024-04-05 at 16 00 56" src="https://github.com/WISVCH/chipcie-website/assets/20283/b72c7330-0119-4705-90ca-6801d2023846">
